export const TABS = {
  Leads: [
    "leadId",
    "runId",
    "businessName",
    "websiteUrl",
    "location",
    "address",
    "phone",
    "email",
    "googleRating",
    "reviewCount",
    "googlePlaceId",
    "googleMapsUrl",
    "contactPageUrl",
    "bookingPageUrl",
    "relevanceScore",
    "acceptedReason",
    "websiteStatus",
    "visibilityScore",
    "visibilityTier",
    "searchPoint",
    "searchRank",
    "opportunityFlags",
    "sourceUrl",
    "status",
    "niche",
    "notes",
    "createdAt",
    "updatedAt",
    "error",
  ],
  ScrapedData: [
    "scrapedId",
    "leadId",
    "runId",
    "title",
    "metaDescription",
    "homepageText",
    "contactPageUrl",
    "bookingPageUrl",
    "visibleEmail",
    "visiblePhone",
    "ctaButtons",
    "trustSignals",
    "status",
    "createdAt",
  ],
  AuditReports: [
    "auditId",
    "leadId",
    "runId",
    "pros",
    "cons",
    "conversionIssues",
    "ctaIssues",
    "uxIssues",
    "trustIssues",
    "offerClarity",
    "bookingFlowProblems",
    "followUpRebookingOpportunity",
    "retentionRevenueLeaks",
    "technicalIssues",
    "score",
    "top5QuickFixes",
    "recommendedServiceOffer",
    "status",
    "createdAt",
  ],
  EmailDrafts: [
    "draftId",
    "leadId",
    "runId",
    "subject",
    "body",
    "followUp",
    "status",
    "createdAt",
    "updatedAt",
  ],
  AgentRuns: [
    "runId",
    "userEmail",
    "niche",
    "location",
    "locationLat",
    "locationLng",
    "leadCount",
    "radiusKm",
    "reviewFilterEnabled",
    "minReviews",
    "maxReviews",
    "searchDepth",
    "websiteFilter",
    "visibilityFilter",
    "opportunityFilter",
    "notes",
    "status",
    "currentStep",
    "progressDone",
    "progressTotal",
    "rawResultsFound",
    "duplicatesRemoved",
    "irrelevantRejected",
    "qualifiedLeads",
    "removedByReviewFilter",
    "removedByRelevanceFilter",
    "removedByVisibilityFilter",
    "removedByWebsiteFilter",
    "removedByOpportunityFilter",
    "removedAsDuplicate",
    "enrichedWithPlaceDetails",
    "finalQualifiedLeads",
    "discoveryMessage",
    "createdAt",
    "updatedAt",
    "contactPreference",
  ],
  AgentLogs: [
    "logId",
    "runId",
    "agent",
    "level",
    "message",
    "leadId",
    "createdAt",
  ],
  Users: [
    "email",
    "name",
    "picture",
    "status",
    "creditsBalance",
    "lifetimeCreditsUsed",
    "lifetimeCreditsAdded",
    "firstSeenAt",
    "lastSeenAt",
    "lastLoginAt",
    "loginCount",
  ],
  LeadUnlocks: [
    "unlockId",
    "userEmail",
    "leadId",
    "feature",
    "creditsCharged",
    "createdAt",
  ],
  CreditTransactions: [
    "transactionId",
    "userEmail",
    "type",
    "credits",
    "balanceAfter",
    "leadId",
    "runId",
    "reason",
    "createdAt",
  ],
  PlaceCache: [
    "googlePlaceId",
    "businessName",
    "formattedAddress",
    "phone",
    "websiteUrl",
    "googleMapsUrl",
    "rating",
    "reviewCount",
    "businessStatus",
    "cachedAt",
    "updatedAt",
    "rawJson",
  ],
  GeocodeCache: [
    "cacheKey",
    "address",
    "lat",
    "lng",
    "cachedAt",
    "updatedAt",
  ],
  SearchCache: [
    "cacheKey",
    "niche",
    "location",
    "radiusKm",
    "reviewFilterEnabled",
    "minReviews",
    "maxReviews",
    "searchDepth",
    "websiteFilter",
    "visibilityFilter",
    "opportunityFilter",
    "cachedAt",
    "updatedAt",
    "rawJson",
  ],
  WebsiteScanCache: [
    "domain",
    "websiteUrl",
    "email",
    "contactPageUrl",
    "bookingPageUrl",
    "websiteStatus",
    "cachedAt",
    "updatedAt",
  ],
  UsageEvents: [
    "eventId",
    "runId",
    "userEmail",
    "type",
    "provider",
    "count",
    "metadata",
    "createdAt",
  ],
};

export const LEAD_STATUSES = [
  "New",
  "Discovered",
  "Scraping",
  "Scraped",
  "Auditing",
  "Audited",
  "Drafting Email",
  "Pending Approval",
  "Phone Only",
  "Approved",
  "Contacted",
  "Interested",
  "Rejected",
  "Failed",
];

export function serializeCell(value) {
  if (value === undefined || value === null) return "";
  if (Array.isArray(value) || typeof value === "object") {
    return JSON.stringify(value);
  }
  return String(value);
}

export function rowToObject(headers, row) {
  const record = {};
  headers.forEach((header, index) => {
    record[header] = row[index] ?? "";
  });
  return record;
}

export function objectToRow(headers, record) {
  return headers.map((header) => serializeCell(record[header]));
}
